import os

file_path = "c:\\Users\\tegra\\OneDrive\\Desktop\\Elisha\\src\\pages\\Study.tsx"

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Target range for 'sociaux' chapter (currently lines 352-431 in 1-indexed)
start_index = 351  # 0-indexed line 352
end_index = 431    # 0-indexed line 431 (inclusive)

new_chapter_content = [
    "                        {activeChapter === 'sociaux' && (\n",
    "                            <JournalSheet title=\"Sociaux\" subtitle=\"La Construction du Stigmate\">\n",
    "                                <div className=\"font-serif text-zinc-300 leading-relaxed text-lg flex flex-col gap-24\">\n",
    "                                    <div className=\"grid md:grid-cols-12 gap-16\">\n",
    "                                        <div className=\"md:col-span-8 space-y-24\">\n",
    "                                            {/* SECTION 1: CONSTRUCTION SOCIALE */}\n",
    "                                            <div className=\"relative pt-32\">\n",
    "                                                <span className=\"text-[24rem] text-red-600 font-black absolute -top-20 -left-20 opacity-10 leading-none pointer-events-none\">C</span>\n",
    "                                                <div className=\"relative z-10 space-y-12\">\n",
    "                                                    <div className=\"space-y-4\">\n",
    "                                                        <h2 className=\"text-sm font-black uppercase tracking-[0.5em] text-red-600\">Partie I</h2>\n",
    "                                                        <h3 className=\"text-6xl font-black text-white italic uppercase tracking-tighter\">La Construction <br />Sociale</h3>\n",
    "                                                    </div>\n",
    "\n",
    "                                                    <p className=\"text-3xl font-light italic text-zinc-200 leading-snug text-justify\">\n",
    "                                                        Comme nous le savons, le travail du sexe n’est pas bien perçu encore aujourd’hui dans la société occidentale. En soit la <GlossaryLink termId=\"stigmatisation\" label=\"stigmatisation\" onSelect={setActiveChapter} /> elle-même ne vient pas des individus mais de la manière que la société perçoit la prostitution.\n",
    "                                                    </p>\n",
    "\n",
    "                                                    <div className=\"grid md:grid-cols-2 gap-12 text-zinc-400 text-lg leading-relaxed text-justify\">\n",
    "                                                        <div className=\"space-y-8\">\n",
    "                                                            <p>Pour mieux comprendre cela on peut se tourner vers le texte de Philippe Riutort. Une phrase importante de son œuvre est celle-ci :</p>\n",
    "                                                            <div className=\"p-10 bg-white shadow-2xl rounded-sm transform -rotate-1 group hover:rotate-0 transition-transform duration-500\">\n",
    "                                                                <p className=\"text-black text-xl font-black italic uppercase leading-tight tracking-tighter text-center\">\n",
    "                                                                    “Le contrôle social peut être défini comme l’ensemble des dispositifs employés dans une société pour assurer le respect des règles édictées”\n",
    "                                                                </p>\n",
    "                                                            </div>\n",
    "                                                            <p>En effet, nous pouvons l’observer dans les règles écrites et non écrits sur les normes sociales à adopter. Le controle social sert à encadrer une société afin qu’ils puissent respecter les valeurs et se conformer aux normes.</p>\n",
    "                                                        </div>\n",
    "                                                        <div className=\"space-y-8\">\n",
    "                                                            <p>Le côté juridique serait lorsqu’on met en place des lois ou des sanctions. En revanche le côté social serait tous ce qui n’est pas écrit mais qui affecte aussi la vie : le regard déshumanisant, les rumeurs ou encore les moqueries.</p>\n",
    "                                                            <p>Un peu plus loin, il nous explique le concept d'<GlossaryLink termId=\"entrepreneurs-moraux\" label=\"entrepreneurs moraux\" onSelect={setActiveChapter} /> (médias, religion, politiciens) qui vont imposer leur vision du monde en créant des stéréotypes.</p>\n",
    "                                                            <p className=\"text-white font-bold italic border-l-2 border-red-600 pl-6\">\n",
    "                                                                La prostitution est entourée d’une étiquette péjorative qui va à l’encontre des valeurs morales occidentales.\n",
    "                                                            </p>\n",
    "                                                        </div>\n",
    "                                                    </div>\n",
    "                                                </div>\n",
    "                                            </div>\n",
    "\n",
    "                                            {/* SECTION 2: ÉTIQUETAGE ET DÉVIANCE */}\n",
    "                                            <div className=\"pt-32 border-t border-white/5 space-y-16\">\n",
    "                                                <div className=\"space-y-4\">\n",
    "                                                    <h2 className=\"text-sm font-black uppercase tracking-[0.5em] text-red-600\">Partie II</h2>\n",
    "                                                    <h3 className=\"text-6xl font-black text-white italic uppercase tracking-tighter\">Étiquetage et <br />Déviance</h3>\n",
    "                                                </div>\n",
    "\n",
    "                                                <div className=\"columns-1 md:columns-2 gap-12 text-zinc-400 text-lg leading-relaxed text-justify space-y-8 text-justify\">\n",
    "                                                    <p>Howard Saul Becker affirme que la réalité de nos comportements sont construits par nos interactions majoritairement influencées par les normes. Lorsqu’un individu va à l’encontre de ces normes, la société peut le traiter comme « étranger ».</p>\n",
    "                                                    \n",
    "                                                    <div className=\"break-inside-avoid p-10 border-l-4 border-red-600 bg-white/5 italic shadow-2xl rounded-sm my-8\">\n",
    "                                                        <p className=\"text-xl text-zinc-300 leading-relaxed font-serif\">« Dès lors qu’une personne est étiquetée, il semble qu’elle soit enfermée en un cercle infernal ne connaissant aucune issue »</p>\n",
    "                                                        <span className=\"text-[10px] font-sans font-black uppercase tracking-widest mt-6 block opacity-50\">— Shlomo Shoham (1970-1991)</span>\n",
    "                                                    </div>\n",
    "\n",
    "                                                    <p>C’est la théorie de l’étiquetage : ce n'est pas l'action qui fait un déviant, mais l'étiquette qu'on lui colle. Le déviant est un « étranger moral ». Becker énonce la « Carrière déviante » : de la déviance primaire (sans conséquences majeures) à la déviance secondaire (rejet, sanctions).</p>\n",
    "                                                    \n",
    "                                                    <div className=\"break-inside-avoid bg-white p-12 shadow-2xl rotate-1 rounded-sm text-black text-center my-12\">\n",
    "                                                        <p className=\"text-2xl font-black italic leading-tight uppercase tracking-tighter mb-4\">\n",
    "                                                            « J’ai l’impression d’être une espèce de prostituée, tout le monde veut savoir ce que je fais à chaque instant... »\n",
    "                                                        </p>\n",
    "                                                        <span className=\"text-[10px] font-sans font-black uppercase tracking-widest block opacity-50\">— Albert Einstein (p.11)</span>\n",
    "                                                    </div>\n",
    "\n",
    "                                                    <p>La religion a fait en sorte que la prostitution soit perçue comme un regard déviant. Comme l’illustre Einstein, le regard de la société peut influencer la construction de l’identité d’un individu quotidiennement.</p>\n",
    "                                                </div>\n",
    "                                            </div>\n",
    "\n",
    "                                            {/* SECTION 3: IMPACTS SUR LES CONDITIONS DE VIE */}\n",
    "                                            <div className=\"pt-32 border-t border-white/5 space-y-16 pb-24\">\n",
    "                                                <div className=\"flex flex-col md:flex-row gap-12 items-start\">\n",
    "                                                    <div className=\"w-24 h-[1px] bg-red-600 mt-6 shrink-0\" />\n",
    "                                                    <div className=\"space-y-6\">\n",
    "                                                        <h2 className=\"text-sm font-black uppercase tracking-[0.5em] text-red-600\">Impacts Humains</h2>\n",
    "                                                        <h3 className=\"text-5xl font-black text-white uppercase tracking-tighter leading-none\">Conditions de vie</h3>\n",
    "                                                    </div>\n",
    "                                                </div>\n",
    "\n",
    "                                                <div className=\"grid md:grid-cols-2 gap-16 text-zinc-400 text-lg leading-relaxed text-justify\">\n",
    "                                                    <div className=\"space-y-12\">\n",
    "                                                        <p className=\"text-2xl text-zinc-300 font-light italic border-l-2 border-red-600/30 pl-8\">\n",
    "                                                            L’exclusion sociale a des répercussions directes sur la : santé physique et mentale, l’accessibilité au logement, et l’emploi.\n",
    "                                                        </p>\n",
    "                                                        <p>\n",
    "                                                            Psychologiquement, l’exposition constante aux jugements péjoratifs affecte l’estime de soi. L’intériorisation de ces perceptions engendre la honte et la dévalorisation personnelle.\n",
    "                                                        </p>\n",
    "                                                        <div className=\"p-10 bg-red-600/5 rounded-[2rem] border border-red-600/10 flex gap-8 items-start\">\n",
    "                                                            <Brain className=\"text-red-600 shrink-0\" size={32} />\n",
    "                                                            <p className=\"text-zinc-300 italic text-lg\">\n",
    "                                                                « Malheureusement ce sont souvent des personnes isolées socialement... c'est compliqué d'extérioriser les réalités de leur travail. »\n",
    "                                                            </p>\n",
    "                                                        </div>\n",
    "                                                    </div>\n",
    "                                                    <div className=\"space-y-8\">\n",
    "                                                        <p>\n",
    "                                                            La pression sociale contribue au développement de l’anxiété, du stress ou de la dépression. La peur d’être reconnu force à vivre dans l’isolement, ce qui limite le réseau de soutien vital.\n",
    "                                                        </p>\n",
    "                                                        <p>\n",
    "                                                            Cette <GlossaryLink termId=\"stigmatisation\" label=\"stigmatisation\" onSelect={setActiveChapter} /> freine la recherche d’aide par crainte d’être mal compris. L’exclusion renforce une précarité déjà extrêmement complexe.\n",
    "                                                        </p>\n",
    "                                                        <div className=\"pt-12 border-t border-zinc-800\">\n",
    "                                                            <p className=\"text-white font-black uppercase tracking-widest text-xs mb-4\">Conclusion Sociologique</p>\n",
    "                                                            <p className=\"text-zinc-500 italic\">\n",
    "                                                                Le déviant est celui à qui l’étiquette a été appliquée avec succès. L'image de la prostitution reste visualisée par rapport aux normes dominantes.\n",
    "                                                            </p>\n",
    "                                                        </div>\n",
    "                                                    </div>\n",
    "                                                </div>\n",
    "                                            </div>\n",
    "                                        </div>\n",
    "\n",
    "                                        {/* SIDEBAR ANALYSIS */}\n",
    "                                        <div className=\"md:col-span-4 border-l-2 border-white/5 pl-12\">\n",
    "                                            <div className=\"sticky top-12 space-y-16\">\n",
    "                                                <div className=\"space-y-8\">\n",
    "                                                    <h3 className=\"text-3xl font-black uppercase text-red-600 tracking-tighter border-b-2 border-red-600 pb-4 italic font-serif\">Analyse de Paire</h3>\n",
    "                                                    <div className=\"space-y-6 text-zinc-500 italic text-lg text-justify\">\n",
    "                                                        <p>La stigmatisation ne reste pas seulement au niveau des idées, elle influence concrètement la perception par les pairs.</p>\n",
    "                                                        <div className=\"p-8 bg-white/5 rounded-3xl border border-white/10 text-zinc-400\">\n",
    "                                                            « Cette vision crée des divisions entre les femmes elles-mêmes, opposant les \"respectables\" aux \"déviantes\". »\n",
    "                                                        </div>\n",
    "                                                    </div>\n",
    "                                                </div>\n",
    "\n",
    "                                                <div className=\"pt-24 opacity-20 group hover:opacity-100 transition-opacity\">\n",
    "                                                    <ShieldCheck size={120} className=\"text-zinc-500 mb-8\" strokeWidth={1} />\n",
    "                                                    <div className=\"text-[10px] font-black tracking-[0.3em] uppercase leading-loose text-zinc-500\">\n",
    "                                                        Sociological Archive<br />Series 2026<br />Project Elisha\n",
    "                                                    </div>\n",
    "                                                </div>\n",
    "                                            </div>\n",
    "                                        </div>\n",
    "                                    </div>\n",
    "                                </div>\n",
    "                            </JournalSheet>\n",
    "                        )\n"
]

lines[start_index:end_index] = new_chapter_content

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Successfully restructured the entire Sociaux chapter.")
